### ISSUE TITLE
Default message does not send anything

### ISSUE THREAD

**Issue by T04435** [appleboy/discord-action#7]
Hi according to the docs there is a `Default message` option:

```
- name: send message
  uses: appleboy/discord-action@master
  with:
    webhook_id: ${{ secrets.WEBHOOK_ID }}
    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
```

When I use this option in my workflow it does not send any message to discord.
Q:
- What is the expected output of the default message?
- When using `message` how can I add a link the the `issue` that triggered the event?

This is what I have

Default message, nothing in Discord
```
name: Discord
on:
  issues:
    types: [opened, labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'bug' }}
    name: Notify new Bug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send test message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        // message: [What to add here to get a link to the issue]
```

Thanks.
