### ISSUE TITLE
Back-ticks in message show up literally

### ISSUE THREAD

**Issue by shaperilio** [appleboy/discord-action#9]
I'd like to send a message with a code fragment. So I tried this:
```yml
    - name: Send message
      if: always()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_ID }}
        webhook_token: ${{ secrets.DISCORD_TOKEN }}
        message: |
          Check out this code:
          ```python
          import os
          ```
```
But I see the three backticks in Discord, rather than `import os` formatted as code. How can I do this?
